### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by sdmydbr9** [fewieden/MMM-TTS#4]
Does this still work. I have installed this because google tts stopped working and I can’t seem to figure out how to make it work. Manually running festival there is output but when I send an alert to the mirror, it doesn’t read out anything

**Comment by fewieden** [comment]
@sdmydbr9 I currently have no setup with this running.

The API still looks the same for the npm module.

The current installation instructions are specified as `sudo apt-get install festival festvox-kallpc16k`. The last part is the default voice. But since you mentioned that you get output running festival manually I would exclude a missing voice for now.

The MM module is logging an error that might come back from the npm module.
https://github.com/fewieden/MMM-TTS/blob/4389af261a75f299d699528a2541d4076824162b/node_helper.js#L24-L29

- Did you check the logs if you can see any errors?
- Can you see this log as well https://github.com/fewieden/MMM-TTS/blob/4389af261a75f299d699528a2541d4076824162b/node_helper.js#L17?

**Comment by sdmydbr9** [comment]
I can see `console.log(`Starting node helper for: ${this.name}`);  `
 
 I have tried various methods to make this work and the only progress I have made so far is entering `   this.sendNotification('MMM-TTS', payload, sender); `
In the alert.js file in the default modules so that it can output a speech everytime a notification is received.
I have no experience in this field so I really have to no idea how to make this work.
This however outputs something, it just say something like “left bracket object object right bracket”. However if I enter a custom text in the alert.js file with mmm-tts notification hook the speech output is just fine. I cannot seem to make the output by making use of the payload.
What Iam trying to achieve is for it to read every alert and notification received. 
Thanks

**Comment by fewieden** [comment]
@sdmydbr9 ok so you get the stuff read out now, just not what you expect.

The problem is the payload sent to the alert module is an object e.g.

```js
{type: "notification", title: "This is a title", message: "I am a message for the alert module"}
```
Check out the [documentation](https://docs.magicmirror.builders/modules/alert.html#developer-notes) for more details.

But the TTS module expects text as a payload. It converts the object to text which is `[object Object]` which is exactly what it is reading out loud.

You can change your function to something like:

```js
this.sendNotification("MMM-TTS", payload.title + " " + payload.message);
```

Which should read out `This is a title I am a message for the alert module` from the example above.

You can also add a log before the call to TTS.

```
console.log('I am going to read', payload);
tts.speak(payload, this.config.voice, this.config.speed, (err) => {
```

If this is readable text it should be read out loud.

**Comment by sdmydbr9** [comment]
Thank you so much. Everything is fixed now.. thank you for this wonderful module
